version: '3.8'
services:
    mongo:
        image: mongo:6.0.2
        container_name: mongodb
        hostname: mongodb
        networks:
            - mongonet
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        healthcheck:
            test: [ "CMD","mongosh","--eval","db.adminCommand('ping')" ]
            interval: 10s
            timeout: 2s
            retries: 5

    mongo-express:
        image: mongo-express:6.0.2
        container_name: mongo-express
        restart: unless-stopped
        networks:
            - mongonet
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: "27017"
        ports:
            - "8081:8081"
        depends_on:
            - mongo


networks:
    mongonet: {}
