services:
    postgres:
        image: postgres:15.0-alpine
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
volumes:
    postgres:
