version: '3.8'
services:
    cassandra1:
        image: docker.io/bitnami/cassandra:latest
        hostname: cassandara1
        networks:
            - cassandranet
        ports:
            - "7000:7000"
            - "9042:9042"
        environment:
            - CASSANDRA_SEEDS=cassandra1,cassandra2
            - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
            - CASSANDRA_DATACENTER=dc1
            - CASSANDRA_PASSWORD_SEEDER=yes
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_USER=user
            - CASSANDRA_PASSWORD=password
            - MAX_HEAP_SIZE=1G
            - HEAP_NEWSIZE=200M
    cassandra2:
        image: docker.io/bitnami/cassandra:latest
        hostname: cassandara2
        networks:
            - cassandranet
        ports:
            - "7001:7000"
            - "9043:9042"
        environment:
            - CASSANDRA_SEEDS=cassandra1,cassandra2
            - CASSANDRA_CLUSTER_NAME=nbd-cassandra-cluster
            - CASSANDRA_DATACENTER=dc1
            - CASSANDRA_PASSWORD_SEEDER=no
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_USER=user
            - CASSANDRA_PASSWORD=password
            - MAX_HEAP_SIZE=1G
            - HEAP_NEWSIZE=200M

networks:
    cassandranet: {}
